### PR TITLE
Fix for ffpicker class help

### LINKED ISSUE #2: [p]ffpicker help error
Using [p]help FFPicker to display the help for the cog results in:
```
[2019-09-17 09:59:52] [ERROR] red: Exception in command 'help'
Traceback (most recent call last):
  File "c:\envs\margaret\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\envs\margaret\lib\site-packages\redbot\core\commands\help.py", line 585, in red_help
    await ctx.bot.send_help_for(ctx, thing_to_get_help_for)
  File "c:\envs\margaret\lib\site-packages\redbot\core\bot.py", line 176, in send_help_for
    return await self._help_formatter.send_help(ctx, help_for)
  File "c:\envs\margaret\lib\site-packages\redbot\core\commands\help.py", line 103, in send_help
    await self.format_cog_help(ctx, help_for)
  File "c:\envs\margaret\lib\site-packages\redbot\core\commands\help.py", line 299, in format_cog_help
    splitted = description.split("\n\n")
AttributeError: 'Command' object has no attribute 'split'
```

### PR DESCRIPTION
**Pull request by aikaterna**
Resolves #2

### CODE REVIEW

**Comment by aikaterna** [comment]
Hmm, strangely enough this is working on a bot that is a little ahead on dev commits on Red, and is not working on a bot that's on 3.1.5 - same traceback that's reported in #2 . Not quite sure what the help differences are in between versions like that.

**Comment by adorabilis** [comment]
That is indeed strange. It works fine for me on a clean 3.1.5 instance. Can you verify?

**Comment by aikaterna** [comment]
If it works for you on a 3.1.5 bot then don't worry about it too much. I have a modified instance I was testing it on alongside a couple plain instances... couldn't really determine where the issue is because on the modified instance I have not done anything to it regarding help.
